apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydjango-deploy
spec:
  selector:
    matchLabels:
      app: mydjango
  template:
    metadata:
      labels:
        app: mydjango
    spec:
      containers:
      - name: mydjango
        image: docker.io/kamal0405/mydjango:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
  apiVersion: v1
  kind: Service
  metadata:
    name: mydjango-service
  spec:
    selector:
      app: mydjango
    ports:
    - port: 8080
      targetPort: 8080
  
